name: habit-tracker-app
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Run npm install
        run: npm i
      - name: Install Ionic CLI
        run: npm install -g @ionic/cli
      - name: Build Application
        run: ionic build --prod
  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18.12.1'
  #     - name: Run npm install
  #       run: npm i
  #     - name: Run tests
  #       run: npm run test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Run npm install
        run: npm i
      - name: Lint code
        run: npm run lint
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.1"
      - name: Run npm install
        run: npm i
      - name: Style check code
        run: npm run style-check
